apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
    tier: database
  name: mysql
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy: {}
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
      - image: mysql:8
        name: mysql
        resources:
          requests:
            memory: "750Mi"
          limits:
            memory: "1250Mi" 
        env:
        - name: MYSQL_DATABASE
          value: pricelist
        - name: MYSQL_PASSWORD
          value: pricelist
        - name: MYSQL_USER
          value: pricelist
        - name: MYSQL_ROOT_PASSWORD
          value: pricelist
        volumeMounts:
        - mountPath: /var/lib/mysql-data/data
          name: mysql-db
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 12
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 12
          periodSeconds: 10
      volumes:
      - name: mysql-db
        persistentVolumeClaim:
          claimName: pricelist-db-pvc
